---
version: 3.0.5
slug: acme_sh2
name: ACME.sh Certs
description: Request certificates using ACME.sh
url: https://github.com/Destarianon/ha.addon.acme_sh
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
boot: manual
init: false
map:
  - ssl:rw
options:
  server: https://acme-v02.api.letsencrypt.org/directory
  certfile: fullchain.pem
  keyfile: privkey.pem
  challenge: http
  dns: {}
schema:
  domains:
    - str
  email: email?
  server: url
  server_rootca: str?
  certfile: str
  keyfile: str
  challenge: list(dns|http|tls)
  keylength: list(2048|3072|4096|ec-256|ec-384|ec-521)?
  valid_to: str?
  dns:
    provider: str?
    env:
      - str?
  debug: bool?